export interface dataLogin  {
  username: string;
  password: string;
}// Generated by https://quicktype.io

export interface infoUser {
  uid:             string;
  displayName:     string;
  photoURL:        string;
  email:           string;
  emailVerified:   boolean;
  phoneNumber:     null;
  isAnonymous:     boolean;
  tenantId:        null;
  providerData:    string[];
  apiKey:          string;
  appName:         string;
  authDomain:      string;
  stsTokenManager: string;
  redirectEventId: null;
  lastLoginAt:     string;
  createdAt:       string;
  multiFactor:     string;
}

// export interface MultiFactor {
//   enrolledFactors: any[];
// }

// export interface ProviderDatum {
//   uid:         string;
//   displayName: string;
//   photoURL:    string;
//   email:       string;
//   phoneNumber: null;
//   providerId:  string;
// }

// export interface StsTokenManager {
//   apiKey:         string;
//   refreshToken:   string;
//   accessToken:    string;
//   expirationTime: number;
// }

export interface carsTypes {

  id: number;
  make: string;
  model: string;
  price: string;

  
}
export type counter = number



